language: python

python:
  - 3.6

env:
  global:
    - secure: "SeIArR+Z4WpmSYgdHADIpsWT4+uphTC5KccHMZoh4bTRSpxBGULm5AA72AFdxdr+TQhryGCJYqrAsf1fUjGF8Yey2cT+Jc7tCvOVA57XLYvs/RSC4TXi/GupUZ8CBgoFo3Jl/dZK3HuKNi8hh9McPNOhZkHMUXtHAFeUZH48qaXRMMqZZgEIm/WQl7bpkCSIgEE1jngKNr6vyY2rkrubZ3z066dLqlHaPK0Ls86oK/tXU/6LV0K/0bGEDqNMm2HwicK99VAjM/9whKnnIxQ1fymryvufeaumgJSCoqSLF1fytiszbd0Koy3nAPOxOFUvAcm7aE8anmNbtZOn0F30z0LTqgKvQJvn/USYQf98zgAGqxkq2YPMlnuu3PVlKqi+a/3sNg1zEufQ1Vo4a1wNymV0EAHXS9+TDxvQutFKDfvJMtywkwEychEwwzHCXzr7lsfjgQc2MFCI8tIe2peJ3D5TXlwjr5EWQoOiGy/6ZpkmoiriZ984Dcnb3+/xdVaRNdZ6FYevKxYHVPCS5HVz8wCjwCBOCBAkptUPX9QHAJT7i513kupmeWVArsc81PJ9oJOTdhv0PJLYGAk2OoDMLiM9oiEH54JyEsXodEVfjQql9qy0LC1hPgiagHXXpkqfkh9RW3zu2XiQbUxCnjWm4z1sWxrdculz5MnkjTIQvuE="


install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge # For sphinxcontrib.autoprogram
  - conda update -q conda 
  - conda info -a
  - conda create -q -n doc-build-environment python=3.6 sphinx pandoc cloud_sptheme doctr pygments_anyscript
  - source activate doc-build-environment
  - pip install sphinxcontrib-fulltoc
  - python setup.py install

before_script:
  - rvm get head || true

script:
  - set -e
  - cd docs;
  - make html-dev;
  - cd ..;
  - doctr deploy --deploy-repo AnyBody/anybody-tutorials dev;
  - git checkout $(git describe --tags `git rev-list --tags --max-count=1`);
  - cd docs;
  - make clean html;
  - cd ..;
  - doctr deploy --deploy-repo AnyBody/anybody-tutorials .;
