language: python

python:
  - 3.7

env:
  global:
    - secure: "DkQV013KPaaMxpEMVxGSV9YjHUIRao6hRXx6qzFvQH1RxsUNj1o8qHY/0AniQnX5mYP2RV8fc71gjoplTwfVFFkIVWtRHCGjp2zO+0c7SlEPZWCrE9jcr7gDfKWEvgWZnlZGKv0aV0BuNDrTq/ASrbpy8672EjyNGiGjC5f5iZek9knGr2UzF5KdSbmYC1alDq/BvmLyTJ7GxCJMEUZtQIL1StuqlVwciC1QjmdH3PZagtuxlRMhtDYbHozCYGtEZieeeo/0FhU0O0aORj0+YbCP5zDFdY0T9Zb9LcF6NLd+jMRxA017zkc6jNX+S5K6hAVlTdURJbtGgzMPJZQDigCnlVrVgmLgGA0lygtOQ/Db7Q+PhhjGcXk3wOfb3jA7q/T9cPplWZq74e6/CfbcveKnZWdjYXZrXrDBr7mlAqbYE5Ko4qQc42xl5r57Ww2/9XrbsKmjXCnn7QM4R6pYgZm5oyK7vC0sh9ZN4iTpfwXtGurkqJytZVACr/OsZIzEtXaJWf+oGqQu0Mf3cRvRpfXdyrTCIXB/nuoLdxeRgKW3mVOnggc0U7EJqZ0JjVdCtBT28uuoe5S0P7BNeHhwoZBKGlZcCkZV/aN6xpLN58cFt3sJvJbgI4xK26IOBHiSfWxhn1OxoEfmaslo1JL2OY6RwY9Nc4VLJCkf/ptzRbA="


install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge # For sphinxcontrib.autoprogram
  - conda update -q conda 
  - conda info -a
  - conda create -q -n doc-build-environment python=3.7 sphinx<2.0 cloud_sptheme doctr pygments_anyscript ipython
  - source activate doc-build-environment

before_script:
  - rvm get head || true

script:
  - set -e
  - make html-dev;
  - doctr deploy --deploy-repo AnyBody/tutorials dev;
  - git checkout $(git describe --tags `git rev-list --tags --max-count=1`);
  - make clean;
  - make html;
  - doctr deploy --build-tags --deploy-repo AnyBody/tutorials .;
